apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: bankapp
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "Test@123"
  MYSQL_DATABASE: "bankappdb"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: "Test@123"